<script>
export default {
  amount: ['金额', 'Amount'],
  amendText: ['修改', 'Modify'],
  backText: ['返回', 'Back'],
  binName: ['库位', 'Bin Name'],
  buyerText: ['客户', 'Buyer'],
  cancel: ['取消', 'Cancel'],
  cancelTradeText: ['取消交易', 'Cancel'],
  cashierList: {
    text1: ['总件数', 'Total'],
    text2: ['会员', 'VIP'],
    text3: ['会员价', 'VIP Price'],
    text4: ['现金', 'Cash'],
    text5: ['银行卡', 'Card'],
    text6: ['移动支付', 'Mobile'],
    text7: ['会员卡', 'VIP Card'],
    text8: ['优惠券', 'Credit Note'],
    text9: ['代收', '代收'],
    text10: ['其他', 'Others'],
    text11: ['已收', 'Received'],
    text12: ['找零', 'Change'],
    text13: ['收款', 'CASH'],
    text14: ['合计', 'TOTAL'],
    text15: ['商品明细', 'Product Details'],
    text16: ['结算明细', 'Payment Details'],
    text17: ['刷卡', 'Card'],
    text18: ['应退', 'Return'],
    text19: ['实退', 'Actual Return'],
    text20: ['应退金额', 'Retrun Amount'],
    text21: ['注意', 'Attention'],
    text22: ['将按收款原路返回', 'Backtrack'],
    text23: ['注意退回赠品及优惠券', 'Attention To Gift And Discount Coupon'],
    text24: ['确定退货?', 'Return Or Not?'],
    text25: ['退货原因', 'Reason'],
    text26: ['整单退货', 'Return'],
    text27: ['姓', 'First Name'],
    text28: ['名', 'Last Name'],
    text29: ['促销', 'Promot'],
    text30: ['挂单', 'Suspend Orders'],
    text31: ['取挂单', 'Take Out Orders'],
    text32: ['申请改价', 'Change Price'],
    text33: ['外场移动支付', '外场移动支付'],
    text34: ['外场刷卡', '外场刷卡'],
    text35: ['代收微信', '代收微信'],
    text36: ['代收刷卡', '代收刷卡'],
    text37: ['代收支付宝', '代收支付宝'],
    text38: ['代收流水号', '代收流水号'],
    text39: ['优惠券号', 'Credit Note No'],
    text40: ['优惠券金额', 'Credit Note Amount'],
    text41: ['公司账户收款', '公司账户收款'],
    text42: ['飞凡收款', '飞凡收款'],
    text43: ['应收', 'RECEIVABLE'],
    text44: ['商城代收', '商城代收'],
    text45: ['完成收银', 'Complete'],
    text46: ['已优惠', 'Discount'],
    text47: ['应收金额', 'Amount'],
    text48: ['结算', 'Payment'],
    text49: ['确定取消吗?', 'Cancel Or Not?'],
    text50: ['促销规则', 'Promotion Rules'],
    text51: ['单项促销', 'Product Promotion'],
    text52: ['整单促销', 'Order Promotion'],
    text53: ['销售员信息', 'Sales Person Information'],
    text54: ['请选择导购员', 'Choose Sales Person'],
    text55: ['库存数为0,暂不能添加该商品', 'The Inventory Is 0, Do Not Allow To Add'],
    text56: ['至少输入三个字符', 'Enter At Least Three Character'],
    text57: ['支付金额不足！', 'Underpayment'],
    text58: ['该版本只可使用一次优惠券', 'The Coupon Can Be Used Only Once'],
    text59: ['当前角色允许修改的最低价是', 'The Discount Price Can Be Modified Is:'],
    text60: ['现金', 'Cash Amount'],
    text61: ['刷卡', 'Card Amount'],
    text62: ['移动支付', 'Mobile Amount'],
    text63: ['交易号不能为空', 'No Transaction'],
    text64: ['点击此按钮返回日结首页', 'Click Back To Daily Settlement Homepage'],
    text65: ['日结时间', 'Daily Time'],
    text66: ['点击此按钮查看日结列表', 'Click To Check Daily Settlement'],
    text67: ['日结小票', 'Daily Settlement'],
    text68: ['未日结销售数据', 'Sales Not Settled'],
    text69: ['未日结退款数据', 'Returns Not Settled'],
    text70: ['日结详情', 'Daily Settlement Details'],
    text71: ['请选择商品', 'Select Product'],
    text72: ['优惠券号不能为空', 'No Credit Note'],
    text73: ['总件数', 'Total Quantity'],
    text74: ['改价成功！', 'Changed Successfully'],
    text75: ['同步成功！', 'Sync Success'],
    text76: ['同步失败！', 'Sync Fail'],
    text77: ['退货单号', 'Return Order']
  },
  cashierText: ['收银员', 'Cashier'],
  classText: ['种类', 'Class'],
  closedText: ['关闭', 'Close'],
  collectionMethod: ['收银方式', 'Collection Method'],
  createDate: ['创建日期', 'Create Date'],
  createTime: ['创建时间', 'Create Time'],
  currency: ['币种', 'Currency'],
  dailySettleHeader: [
    ['编号', 'No.'],
    ['项目', 'Item'],
    ['描述', 'Quantity/Amount']
  ],
  dailySettleList: [
    ['销售单数', 'Successful Orders'],
    ['销售货品数量', 'Sales Quantity'],
    ['原价总计', 'Total MRP Amount'],
    ['折扣总计', 'Total Saving'],
    ['折后总计', 'Net Sales Amount'],
    ['现金支付小计', 'Cash Payment'],
    ['银行卡支付小计', 'Card Payment'],
    ['移动支付小计', 'Molible Payment'],
    ['代金券支付小计', 'Credit Note Payment'],
    ['退货单量', 'Return Orders'],
    ['退货数量', 'Return Quantity'],
    ['退货金额总计', 'Total Return Amount'],
    ['现金退款小计', 'Cash Return Subtotal'],
    ['银行卡退款小计', 'Card Return Subtotal'],
    ['移动支付退款小计', 'Molible Return Subtotal'],
    ['代金券退款小计', 'Credit Note Return Subtotal'],
    ['当日现金净收款额', 'Net Cash Payment Received'],
    ['当日银行卡净收款额', 'Net Card Payment Received'],
    ['当日移动支付净收款额', 'Net Mobile Payment Received'],
    ['当日代金券净收款额', 'Net Credit Note Payment Received'],
    ['新增会员数', 'New VIP']
  ],
  date: ['日期', 'Date'],
  deleteText: ['删除', 'Delete'],
  deleteTipText: ['确定删除?', 'Delete Or Not?'],
  descriptionEn: ['英文描述', 'Description'],
  detailText: ['明细', 'Details'],
  downloadPrintPlugin: ['下载打印插件', 'Download The Plugin'],
  downPage: ['下一页', 'Down'],
  eachPage: ['每页', 'Per'],
  editText: ['编辑', 'Edit'],
  employeeAccount: ['账号', 'Username'],
  employeeEmail: ['邮箱', 'Email'],
  employeeNo: ['工号', 'ID'],
  employeeName: ['姓名', 'Name'],
  employeePassword: ['密码', 'Password'],
  employeeStatus: ['员工状态', 'Active/Inactive'],
  employeeStop: ['停用', 'Inactive'],
  employeeType: ['类型', 'Type'],
  employeeTarget: ['日指标', 'Daily Indicators'],
  employeeUsing: ['启用', 'Active'],
  errorTipText: {
    text1: ['请选择时间', 'Select Time'],
    text2: ['请输入新密码!', 'Enter New Password!'],
    text3: ['请输入确认密码!', 'Enter Confirm Password!'],
    text4: ['密码输入不一致!', 'Inconformity Password!'],
    text5: ['文件格式与模板不匹配!', 'The File Format Does Not Match The Template.'],
    text6: ['姓不能为空', 'No First Name'],
    text7: ['名不能为空', 'No Last Name'],
    text8: ['电话号码不能为空', 'No Mobile'],
    text9: ['电话号码不对', 'Mobile Is Fault'],
    text10: ['请输入账号!', 'Enter Username!'],
    text11: ['请输入密码!', 'Enter Password!'],
    text12: ['该会员未下单', 'No Result']
  },
  exportText: {
    text1: ['销售主单数据导出', 'Sales Order Export'],
    text2: ['销售详细数据导出', 'Sales Details Export'],
    text3: ['销售付款数据导出', 'Sales Payment Export'],
    text4: ['所有库存数据导出', 'Inventory Export'],
    text5: ['员工业绩导出', 'Employee Performance Export'],
    text6: ['导出', 'Export']
  },
  firstPage: ['首页', 'First'],
  grossAmount: ['含税金额', 'Gross Amount'],
  gstAmount: ['税额', 'GST Amount'],
  gstValue: ['税率', 'GST%'],
  homePageName: ['首页', 'HOME'],
  homePT: {
    bCTitle: ['今日营业状况', 'Business Today'],
    bCTitle1: ['成交量', 'Turnover'],
    bCTitle2: ['销售', 'Sale'],
    bCTitle3: ['退货', 'Return'],
    bCTitle4: ['会员', 'VIP'],
    bCTitle5: ['交易完成率', 'Transaction Completion Rate'],
    bCTitle6: ['收款方式占比', 'Payment Method'],
    bSRTitle: ['畅销商品七日排行榜', 'Product By Amount Sold (week)'],
    nBTitle: ['消息通知', 'NOTICE'],
    rankText1: ['(金额)', '(Amount)'],
    rankText2: ['(数量)', '(Quantity)'],
    selectedData1Text1: ['升序', 'Up'],
    selectedData1Text2: ['降序', 'Down'],
    selectedData2Text1: ['待审核调拨单', 'Pending Approval'],
    selectedData2Text2: ['待发货调拨单', 'Pending Fulfillment'],
    selectedData2Text3: ['待接收调拨单', 'Pending Receipt'],
    sPTitle: ['每日导购员业绩', 'Sales Person Daily'],
    tRTitle: ['七日营业额状况', 'Sales List(week)'],
    wHeadTd1: ['调拨单号', 'ID'],
    wHeadTd2: ['发出门店', 'From Shop'],
    wHeadTd3: ['接收门店', 'To Shop'],
    wHeadTd4: ['创建时间', 'Create Time'],
    wHeadTd5: ['更新时间', 'Update Time'],
    wETitle: ['待处理事项', 'Pending Matters']
  },
  importText: {
    text1: ['导入', 'Import']
  },
  inventory: {
    taskStatus: [
      {
        id: 0,
        text: ['草稿', 'Draft']
      },
      {
        id: 1,
        text: ['完成', 'Complete']
      }
    ],
    orderStatus: [
      {
        id: 0,
        text: ['草稿', 'Draft']
      },
      {
        id: 1,
        text: ['待审批', 'Pending Approval']
      },
      {
        id: 2,
        text: ['已审批', 'Approved']
      }
    ],
    transferStatus: [
      {
        id: -1,
        text: ['草稿', 'Draft']
      },
      {
        id: 0,
        text: ['待审核', 'Pending Approval']
      },
      {
        id: 1,
        text: ['待发货', 'Pending Fullfillment']
      },
      {
        id: 2,
        text: ['待收货', 'Pending Receipt']
      },
      {
        id: 3,
        text: ['完成', 'Complete']
      }
    ],
    taskType: [
      {
        id: 1,
        text: ['集团盘点', 'All Location']
      },
      {
        id: 2,
        text: ['单仓盘点', 'Single Location']
      }
    ],
    taskCoverage: [
      {
        id: 1,
        text: ['全部SKU', 'All SKU']
      },
      {
        id: 2,
        text: ['全部SKU(不含库存为0)', 'All SKU(Inventory Not Null)']
      },
      {
        id: 3,
        text: ['部分商品', 'Part Of SKU']
      }
    ]
  },
  inventoryText: {
    text1: ['审核通过', 'Approved'],
    text2: ['驳回', 'Reject'],
    text3: ['盘点单号', 'Order No.'],
    text4: ['盘点单状态', 'Order Status'],
    text5: ['总盈亏金额', 'Total Profit And Loss'],
    text6: ['库存数', 'On Hand'],
    text7: ['盘点数', 'Inventory Count'],
    text8: ['差异数', 'Difference'],
    text9: ['盈亏金额', 'Profit And Loss'],
    text10: ['关联任务单号', 'Related'],
    text11: ['选择商品', 'Select Product Name'],
    text12: ['选择商品范围', 'Select Product Coverage'],
    text13: ['盘点人', 'Checker'],
    text14: ['商品范围', 'Product Coverage'],
    text15: ['仓库范围', 'Location Coverage'],
    text16: ['请选择仓库范围', 'Select Location Coverage'],
    text17: ['请选择仓库', 'Select Location'],
    text18: ['创建盘点单', 'Create Order'],
    text19: ['已成功创建盘点单!', 'Created Successfully!'],
    text20: ['任务单号', 'Play No.'],
    text21: ['盘点类型', 'Type'],
    text22: ['任务单号', 'ID'],
    text23: ['任务单状态', 'Task Status'],
    text24: ['任务单创建时间', 'Task Create Time'],
    text25: ['盘点单创建时间', 'Order Create Time'],
    text26: ['盘点单状态', 'Order Status'],
    text27: ['调出仓库', 'From Shop'],
    text28: ['调入仓库', 'To Shop'],
    text29: ['要货日期', 'Requiring Date'],
    text30: ['发货', 'Fulfill'],
    text31: ['收货', 'Receive'],
    text32: ['审批拒绝', 'Reject'],
    text33: ['可用数', 'Available Quantity'],
    text34: ['调拨数量', 'Quantity'],
    text35: ['UPC/商品名称/SKU', 'UPC/Product Name/SKU'],
    text36: ['SKU不能为空', 'SKU Not Null'],
    text37: ['数量不能小于1', 'Quantity Greater Than 1'],
    text38: ['调拨单号', 'Transfer No'],
    text39: ['状态', 'Status'],
    text40: ['创建人', 'Create By'],
    text41: ['任务单创建日期', 'Task Create Date'],
    text42: ['盘点单创建日期', 'Order Create Date']
  },
  jobTitle: ['职位', 'Job Title'],
  lastPage: ['尾页', 'End'],
  listItem: ['条', 'Line'],
  location: ['仓库', 'Shop No.'],
  loginPageName: ['登录', 'Login'],
  loginPT: {
    autoLoginText: ['下次自动登录', 'Auto Login'],
    errorText1: ['请先输入用户名', 'Enter Username'],
    errorText2: ['请先输入密码', 'Enter Password'],
    errorText3: ['请选择语言', 'Choose Languages'],
    forgetPwdText: ['忘记密码？', 'Forget Password?'],
    loginText: ['登录', 'Login'],
    placeHolder1: ['请输入用户名', 'Enter Username'],
    placeHolder2: ['请输入密码', 'Enter Password'],
    placeHolder3: ['请选择语言', 'Choose languages']
  },
  memoText: ['备注', 'Memo'],
  moneyMark: ['¥', 'Rs.'],
  moreTimeText: ['连接超时，请检查网络', 'Please Check Your Network'],
  mrp: ['原价', 'MRP'],
  netAmount: ['不含税金额', 'Net Amount'],
  newText: ['新增', 'New'],
  noData: ['数据为空', 'No Result'],
  noText: ['序号', 'No.'],
  operate: ['操作', 'Action'],
  orderNo: ['单号', 'ID'],
  pageHeader: {
    personListText1: ['退出登录', 'Logout'],
    menu1Text: ['首页', 'Home'],
    menu2Text: ['收银', 'Cash'],
    menu21Text: ['下单', 'Order'],
    menu22Text: ['下单列表', 'Order List'],
    menu23Text: ['收银', 'Cash'],
    menu24Text: ['收银小票', 'Cash Register Receipts'],
    menu25Text: ['退货', 'Return'],
    menu26Text: ['退货列表', 'Return Order List'],
    menu27Text: ['日结', 'Daily Settlement'],
    menu28Text: ['会员', 'VIP'],
    menu29Text: ['切换门店', '切换门店'],
    menu3Text: ['库存管理', 'Inventory'],
    menu31Text: ['调拨单', 'Transfer Order'],
    menu32Text: ['库存查询', 'Inventory Search'],
    menu33Text: ['盘点任务单', 'Inventory Count Plan'],
    menu34Text: ['盘点单', 'Inventory Count Order'],
    menu4Text: ['报表分析', 'Report'],
    menu41Text: ['商品库存明细统计', 'Inventory Details'],
    menu42Text: ['门店达标率统计', 'Shop Quanlified Rate'],
    menu43Text: ['商品销售明细统计', 'Product Sold Details'],
    menu44Text: ['店员达标率统计', 'Sales Person Qualified Rate'],
    menu45Text: ['小票数据统计', 'Settlement Data Analyze'],
    menu46Text: ['销售数据导出', 'Sales Data Export'],
    menu47Text: ['进销存明细报表', '进销存明细报表'],
    menu48Text: ['销售汇总表', 'Total Sales Report'],
    menu49Text: ['销售排行榜', 'Sales Chart'],
    menu410Text: ['销售日报明细表', 'Daily Sales Details'],
    menu5Text: ['设置', 'Setup'],
    menu51Text: ['导购设置', 'New Employee'],
    menu52Text: ['日结时间设置', 'Daily Settled Time'],
    menu53Text: ['员工硬指标', 'Employee Target'],
    menu54Text: ['手动同步', 'Manual Sync'],
    menu55Text: ['密码修改', 'Set Password']
  },
  pageText0: ['第', ' '],
  pageText1: ['页', ' '],
  pageText2: ['共', ' '],
  pageText3: ['页  合计', '   Total:'],
  pageText4: ['条', ''],
  pageInputText: [
    ['请扫描/手动输入...', 'Scanning/Enter'],
    ['请输入销售单号', 'Enter Sales Order'],
    ['请输入SKU', 'Enter SKU'],
    ['请输入商品名称', 'Enter Product Name'],
    ['请输入会员电话号', 'Enter VIP Telephone'],
    ['请输入商品信息', 'Product Information'],
    ['请输入...', 'Enter...']
  ],
  payMethodText: ['付款方式', 'Payment Method'],
  payType: [
    {
      id: 0,
      text: ['现金', 'Cash']
    },
    {
      id: 1,
      text: ['刷卡', 'Bank Card']
    },
    {
      id: 2,
      text: ['移动支付', 'Mobile']
    },
    {
      id: 3,
      text: ['优惠券', 'Credit Note']
    },
    {
      id: 4,
      text: ['会员卡', 'VIP Card']
    }
  ],
  phoneText: ['电话', 'Mobile'],
  print: ['打印', 'Print'],
  print1920PageName: ['打印调拨单', 'Transfer Order'],
  print291PageName: ['收银小票', 'Cash Register Receipts'],
  print291RPageName: ['收银小票', 'Cash Register Receipts'],
  print291ZHPageName: ['收银小票', 'Cash Register Receipts'],
  print505PageName: ['日结零售单', 'DAILY SETTLEMENT'],
  print505PageTitle: ['日结零售单', 'DAILY SETTLEMENT'],
  print505PT: {
    text1: ['终端名称', 'Shop No.'],
    text2: ['日结时间', 'Daily Time'],
    text3: ['打印时间', 'Print Time'],
    text4: ['交款人签字', 'FD Cashier Signature'],
    text5: ['收款人签字', 'Shop Signature']
  },
  productClass: {
    class1: ['一级品类', 'First Class'],
    class2: ['二级品类', 'Second Class'],
    class3: ['三级品类', 'Third Class'],
    class4: ['四级品类', 'Forth Class']
  },
  productName: ['商品名称', 'Product Name'],
  quantity: ['数量', 'Quantity'],
  rate: ['售价', 'Rate'],
  returnReasonList: [
    ['尺寸/大小问题', 'Size'],
    ['颜色/款式问题', 'Color/Design'],
    ['材质/面料问题', 'Material'],
    ['功能/效果问题', 'Function/Result'],
    ['参数/规格问题', 'Description/Son/Specification'],
    ['商品质量问题', 'Commodimodity Quality'],
    ['其他原因', 'Others']
  ],
  returnDate: ['退货日期', 'Return Date'],
  returnTime: ['退货时间', 'Return Time'],
  salesDate: ['销售日期', 'Sales Date'],
  salesTime: ['销售时间', 'Sales Time'],
  salesOrderStatus: {
    text1: ['待付款', 'Pending Payment'],
    text2: ['部分付款', 'Partly Paid'],
    text3: ['已付款', 'Paid'],
    text4: ['已退货', 'Returned']
  },
  salesOrderText: ['销售单号', 'Sales Order'],
  salesText: ['销售员', 'Sales Person'],
  saveText: ['保存', 'Save'],
  searchText: ['搜索', 'Search'],
  searchBoxCrl: ['查询条件', 'Search Criteria'],
  setPassword: {
    text1: ['新密码', 'New Password'],
    text2: ['确认密码', 'Confirm Password'],
    text3: ['请输入新密码', 'Enter New Password'],
    text4: ['请输入确认密码', 'Enter Confirm Password'],
    text5: ['修改登录密码', 'Change Login Password']
  },
  shopNo: ['商铺号', 'Shop No.'],
  shopOwner: ['店长', 'Shopowner'],
  shopSignatory: ['商铺签约人', 'Shop Signatory'],
  sku: ['SKU', 'SKU'],
  skuNo: ['SKU No.', 'SKU No.'],
  specification: ['规格', 'Specification'],
  syncText: {
    text1: ['员工同步', 'Staff Data Sync'],
    text2: ['商品档案同步', 'Product Data Sync'],
    text3: ['促销同步', 'Promotion Data Sync'],
    text4: ['门店仓库同步', 'Store Data Sync']
  },
  submit: ['提交', 'Submit'],
  subtotal: ['小计', 'Subtotal'],
  successText: ['成功!', 'Success!'],
  sureText: ['确定', 'OK'],
  templateText: ['下载模板', 'Template'],
  total: ['合计', 'Total'],
  transactionNo: ['交易号', 'Transaction No'],
  transactionType: ['交易类型', 'Transaction Type'],
  unit: ['单位', 'Unit'],
  unitPrice: ['单价', 'Rate'],
  upc: ['UPC', 'UPC'],
  upPage: ['上一页', 'Up'],
  vipNo: ['会员号', 'VIP No.'],
  vipOrPhone: ['会员电话号', 'VIP Telephone'],
  vendorText: ['供应商货号', 'Vendor Code']
}
</script>
